sonar.organization=zecklab
sonar.projectKey=ZeckLab_OC-P10-CI-CD-bobapp

# Back-end
sonar.sources=back/src/main/java
sonar.tests=back/src/test/java
sonar.java.coveragePlugin=jacoco
sonar.java.binaries=back/target/classes
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# Front-end
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info